version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detail:
    format: '%(color)s%(asctime)s|%(levelname)s|%(module)s|%(funcName)s|%(filename)s:%(lineno)d|%(end_color)s%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

loggers:

  debug:
    handlers: [console]
    propagate: true
  harp:
    handlers: [all]
    propagate: false  
  tornado.access:
    handlers: [all]
    propagate: false
  tornado.application:
    handlers: [all]
    propagate: false
  tornado.general:
    handlers: [all]
    propagate: false

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: detail
    stream: ext://sys.stdout
  all:
    class: logging.handlers.TimedRotatingFileHandler
    level: NOTSET
    formatter: detail
    when: H
    backupCount: 7
    filename: ../logs/all.log
  harp:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detail
    when: D
    backupCount: 7
    filename: ../logs/harp.log
  tornado:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detail
    when: D
    backupCount: 7
    filename: ../logs/tornado.log

root:
  level: INFO
  handlers: [console, all]
  propagate: true
